#
# References
#   https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md
#

trigger:
  branches:
    exclude:
      - docs
      - gh-pages

schedules:
  - cron: "10 4 * * 6"
    displayName: "Weekly"
    branches:
      include:
        - main

variables:
  - name: vcpkg.commit
    value: "a34c873a9717a888f58dc05268dea15592c2f0ff" # tag 2024.03.25
  - name: vcpkg.feature.flags
    value: "registries,binarycaching,manifests"
  - name: vcpkg.default.binary.cache
    value: $(Build.BinariesDirectory)/vcpkg-caches
  - name: vcpkg.downloads
    value: $(Build.BinariesDirectory)/vcpkg-caches

jobs:
  - job: Build
    pool:
      vmImage: "windows-2022" 
    # strategy:
    #   matrix:
    #     release_x64:
    #       build.platform: x64
    #       build.configuration: Release
    #       vcpkg.target.triplet: x64-windows
    steps:
      - powershell: New-Item -Type Directory -Force ${env:VCPKG_DEFAULT_BINARY_CACHE}
      - task: Cache@2
        inputs:
          key: "2023-12-10 | vcpkg | x64"
          restoreKeys: |
            "2023-12-10 | vcpkg | x64"
            "2023-07 | vcpkg | x64"
          path: $(vcpkg.default.binary.cache)

      - powershell: |
          vcpkg install --debug --x-install-root "$(Build.SourcesDirectory)/externals"
          vcpkg integrate install
        displayName: "Setup Vcpkg"
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows
          VCPKG_MANIFEST_DIR: $(Build.SourcesDirectory)

      - powershell: nuget restore windows-experiment.sln
        displayName: "Restore NuGet"

      - task: VSBuild@1
        inputs:
          solution: windows-experiment.sln
          platform: "x64" # x64|Win32
          configuration: "Debug" # Debug|Release
          clean: true
          msbuildArchitecture: "x64"
          logFileVerbosity: detailed

      - task: VSTest@2
        inputs:
          testSelector: "testAssemblies"
          platform: "x64" # x64|Win32
          configuration: "Debug" # Debug|Release
          vsTestVersion: latest
          runSettingsFile: "UnitTest1/mta.runsettings"
          testAssemblyVer2: "x64\\Debug\\UnitTest*.dll"
