#
# References
# - https://github.com/sonarsource-cfamily-examples/windows-msbuild-gh-actions-sc
# - https://github.com/sonarsource-cfamily-examples/windows-msbuild-vscoverage-gh-actions-sc
# - https://docs.sonarsource.com/sonarqube-server/2025.1/analyzing-source-code/test-coverage/c-family-test-coverage
# - https://docs.sonarsource.com/sonarqube-server/analyzing-source-code/analysis-parameters
#
name: Analysis

on:
  push:
    branches-ignore:
      - docs
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    env:
      SONAR_USER_HOME: "${{ github.workspace }}/.sonar"
      # VCPKG_DOWNLOADS: "${{ github.workspace }}/packages"
      # VCPKG_DEFAULT_BINARY_CACHE: "${{ github.workspace }}/packages"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - uses: darenm/Setup-VSTest@v1.3
      - uses: NuGet/setup-nuget@v2
        with:
           nuget-version: '6.x'
      - uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v6

      - uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgDirectory: "C:/vcpkg"
          vcpkgGitCommitId: "ef7dbf94b9198bc58f45951adcf1f041fcbc5ea0" # 2025.06.13
          runVcpkgInstall: false

      - name: "Run vcpkg, NuGet Restore"
        run: |
          vcpkg integrate install
          # nuget restore windows-experiment.sln
          nuget restore packages.config -SolutionDirectory .

      - name: "Run build-wrapper(x64/Debug)"
        run: |
          build-wrapper-win-x86-64 --out-dir "bw-output" `
            MSBuild windows-experiment.sln "/t:Shared1;Shared2;App1;UnitTestApp1" /p:platform="x64" /p:configuration="Debug" `
              /nodeReuse:false /p:BuildProjectReferences=false
        env:
          VCPKG_FEATURE_FLAGS: "registries,binarycaching,manifests"

      - name: "Run VSTest(x64/Debug)" # https://github.com/sonarsource-cfamily-examples/windows-msbuild-vscoverage-gh-actions-sc
        run: |
          vstest.console.exe /framework:frameworkuap10 UnitTestApp1.build.appxrecipe `
            /EnableCodeCoverage /Collect:"Code Coverage;Format=Xml" `
            /ResultsDirectory:"${{ github.workspace }}/x64" `
            /Settings:"${{ github.workspace }}/test.runsettings"
        working-directory: x64/Debug/UnitTestApp1

      - uses: actions/cache@v4.3.0
        with:
          key: "sonar-${{ runner.os }}"
          path: "${{ github.workspace }}/.sonar" # SONAR_USER_HOME

      - uses: actions/cache@v4.3.0
        if: ${{ false }}
        with:
          key: "vcpkg-${{ runner.os }}"
          path: "${{ github.workspace }}/packages"

      - uses: SonarSource/sonarqube-scan-action@v6
        with: # todo: separate sonar.links.ci for triggers
          args: >
            --define "sonar.token=${{ secrets.SONAR_TOKEN }}"
            --define "sonar.cfamily.build-wrapper-output=bw-output"
            --define "sonar.cfamily.vscoveragexml.reportsPath=x64/*/*.xml"
