#
# References
#   https://github.com/sonarsource-cfamily-examples/windows-cmake-gh-actions-sc
#   https://github.com/sonarsource-cfamily-examples/windows-msbuild-gh-actions-sc
#   https://devblogs.microsoft.com/cppblog/vcpkg-2023-06-20-and-2023-07-21-releases-github-dependency-graph-support-android-tested-triplets-xbox-triplet-improvements-and-more
#   https://devblogs.microsoft.com/cppblog/vcpkg-integration-with-the-github-dependency-graph
#
name: Analysis

on:
  push:
    branches-ignore:
      - docs
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest

    env:
      SONAR_USER_HOME: "${{ github.workspace }}/.sonar"
      # VCPKG_DOWNLOADS: "${{ github.workspace }}/packages"
      # VCPKG_DEFAULT_BINARY_CACHE: "${{ github.workspace }}/packages"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - uses: NuGet/setup-nuget@v2
        with:
           nuget-version: '6.x'
      - uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5

      - uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgDirectory: "C:/vcpkg"
          vcpkgGitCommitId: "ef7dbf94b9198bc58f45951adcf1f041fcbc5ea0" # 2025.06.13
          runVcpkgInstall: false

      - name: "Run vcpkg-integrate"
        run: vcpkg integrate install
        shell: pwsh

      - name: "Run NuGet Restore"
        run: |
          nuget restore windows-experiment.sln
        shell: pwsh

      - name: "Run build-wrapper"
        run: |
          build-wrapper-win-x86-64 --out-dir bw-output `
            MSBuild App1/App1.vcxproj /t:rebuild /nodeReuse:false /p:platform="x64" /p:configuration="Debug" /p:BuildProjectReferences=false
        shell: pwsh
        env:
          VCPKG_FEATURE_FLAGS: "registries,binarycaching,manifests"

      - uses: actions/cache@v4.2.3
        with:
          key: "sonar-${{ runner.os }}"
          path: "${{ github.workspace }}/.sonar" # SONAR_USER_HOME

      - uses: actions/cache@v4.2.3
        if: ${{ false }}
        with:
          key: "vcpkg-${{ runner.os }}"
          path: "${{ github.workspace }}/packages"

      - uses: SonarSource/sonarqube-scan-action@v5.2.0
        with: # --define sonar.verbose=true?
          args: >
            --define sonar.cfamily.build-wrapper-output="bw-output"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
