#
# References
#   https://github.com/sonarsource-cfamily-examples/windows-msbuild-gh-actions-sc
#
name: Analysis

on: [push, pull_request, workflow_dispatch]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest

    env:
      SONAR_USER_HOME: "${{ github.workspace }}/.sonar"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - uses: NuGet/setup-nuget@v1.2.0

      - uses: SonarSource/sonarcloud-github-c-cpp@v2.0.2

      - uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgDirectory: "C:/vcpkg"
          vcpkgGitCommitId: "3508985146f1b1d248c67ead13f8f54be5b4f5da" # 2024.08.23
          vcpkgJsonGlob: "**/vcpkg.json"
          runVcpkgInstall: true
        env:
          VCPKG_FEATURE_FLAGS: "registries,binarycaching,manifests"
          VCPKG_DEFAULT_TRIPLET: "x64-windows"
          # VCPKG_INSTALLED_DIR: ${{ github.workspace }}/externals

      - name: "Run vcpkg-integrate"
        run: vcpkg integrate install
        shell: pwsh

      - name: "Run NuGet Restore"
        run: |
          nuget restore windows-experiment.sln
        shell: pwsh

      - name: "Run build-wrapper"
        run: |
          build-wrapper-win-x86-64 --out-dir bw-output MSBuild App1/App1.vcxproj /t:rebuild /nodeReuse:false /p:platform="x64" /p:configuration="Debug" /p:BuildProjectReferences=false
        shell: pwsh

      - uses: actions/cache@v4.0.2
        with:
          key: "sonar-${{ runner.os }}"
          path: "${{ github.workspace }}/.sonar" # SONAR_USER_HOME

      - name: "Run sonar-scanner"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner --define sonar.verbose=true --define sonar.cfamily.build-wrapper-output="bw-output"
