name: Deploy

# manual deploy
on: 
  push:
    branches:
      - support/msixbundle
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: [ self-hosted, Windows, CodeSign ]

    env:
      VCPKG_DOWNLOADS: "${{ github.workspace }}/packages"
      VCPKG_DEFAULT_BINARY_CACHE: "${{ github.workspace }}/packages"

    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - uses: actions/cache@v4.2.3
        with:
          key: "github-dependency-cache-0.2438.0"
          path: "${{ github.workspace }}/packages"

      - uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgDirectory: "C:/vcpkg"
          vcpkgGitCommitId: "ef7dbf94b9198bc58f45951adcf1f041fcbc5ea0" # 2025.06.13
          vcpkgJsonGlob: "**/vcpkg.json"
          runVcpkgInstall: true
        env:
          VCPKG_FEATURE_FLAGS: "registries,binarycaching,manifests,dependencygraph"
          VCPKG_DEFAULT_TRIPLET: "x64-windows"

      - name: "Run vcpkg integrate"
        run: vcpkg integrate install
        shell: pwsh

      - name: "Run NuGet Restore"
        run: |
          nuget restore windows-experiment.sln
        shell: pwsh

      - name: "Run appxmanifest.ps1"
        id: appxmanifest
        run: |
          $Version = $(./scripts/headver.ps1 -Build ${{ github.run_number }})
          Write-Output "version=$Version" >> $env:GITHUB_ENV
          ./scripts/update-appxmanifest.ps1 `
            -ManifestPath "./Package/Package.appxmanifest" `
            -Version $Version
        shell: pwsh

      - name: "Run publish.ps1"
        run: |
          MSBuild windows-experiment.sln `
            /p:Platform=x64 `
            /p:AppxBundlePlatforms=x64 `
            /p:Configuration=Debug `
            /p:UapAppxPackageBuildMode=SideloadOnly `
            /p:AppxPackageDir="${{ github.workspace }}/outputs" `
            /p:GenerateAppxPackageOnBuild=true
          Write-Output "${{ steps.appxmanifest.outputs.version }}"
          Get-ChildItem "${{ github.workspace }}/outputs"
        shell: pwsh

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: outputs
          path: |
            outputs/Package_0.2438*/*.ps1
            outputs/Package_0.2438*/*.appxsym
            outputs/Package_0.2438*/*.msixbundle
          if-no-files-found: error
