#
# References
#   https://devblogs.microsoft.com/cppblog/vcpkg-2023-06-20-and-2023-07-21-releases-github-dependency-graph-support-android-tested-triplets-xbox-triplet-improvements-and-more
#   https://devblogs.microsoft.com/cppblog/vcpkg-integration-with-the-github-dependency-graph
#
name: Update(Dependency)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  vcpkg_dependency:
    runs-on: windows-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VCPKG_DOWNLOADS: "${{ github.workspace }}/packages"
      VCPKG_DEFAULT_BINARY_CACHE: "${{ github.workspace }}/packages"

    steps:
      - uses: actions/checkout@v3

      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - uses: actions/cache@v3
        with:
          key: "github-dependency-cache-0.2349.0"
          path: "${{ github.workspace }}/packages"

      - uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgDirectory: "C:/vcpkg"
          vcpkgGitCommitId: "8eb57355a4ffb410a2e94c07b4dca2dffbee8e50" # 2023.10.19
          vcpkgJsonGlob: "**/vcpkg.json"
          runVcpkgInstall: true
        env:
          VCPKG_FEATURE_FLAGS: "registries,binarycaching,manifests,dependencygraph"
          VCPKG_DEFAULT_TRIPLET: "x64-windows"

      - name: "Run vcpkg-integrate"
        run: vcpkg integrate install

      - name: "Run NuGet Restore"
        run: |
          nuget restore App1.sln

      - name: "Run MSBuild"
        run: |
          MSBuild App1/App1.vcxproj /p:platform="x64" /p:configuration="Debug"
